### ISSUE TITLE
有个sklearn报错，应该怎么搞？

### ISSUE THREAD

**Issue by huomqh** [1033020837/WechatGameScript#7]
Traceback (most recent call last):
  File "C:/Users/xxxx-hp/Desktop/Python/WechatGameScript-master/main.py", line 1, in <module>
    import img_tool
  File "C:\Users\xxxx-hp\Desktop\Python\WechatGameScript-master\img_tool.py", line 150, in <module>
    lr = pickle.load(fr)
ImportError: No module named 'sklearn'

Process finished with exit code 1

**Comment by 1033020837** [comment]
https://www.cnblogs.com/lyr2015/p/7891069.html
你参考这个安装吧
